app:
    resource: "@AppBundle/Controller/"
    type: annotation

public_access:
    resource: "@AppBundle/Controller/PublicAccess"
    type: annotation
    prefix: /public

socket:
    resource: "@SocketBundle/Resources/config/routing.yaml"
